export const ProjectTimeLineCardData = [
    {
      id: "1",
      heading: "Make an E-Commerce Website for a Brand Store",
      tags: ["web"],
      timeline: "some timeline data",
      status: "Ongoing",
      milestone: "Next milestone: Dec 5th",
      task: "Follow up with manager",
    },
    {
      id: "2",
      heading: "Website technical maintenance project",
      tags: ["web"],
      timeline: "some timeline data",
      status: "Completed",
      milestone: "Next milestone: Jan 1st",
      task: "Follow up with manager",
    },
    {
      id: "3",
      heading: "WordPress website speed and SEO Optimization",
      tags: ["web"],
      timeline: "some timeline data",
      status: "Drafts",
      milestone: "Next milestone: in 3 days",
      task: "Follow up with manager",
    },
    {
      id: "4",
      heading: "WordPress website speed and SEO Optimization",
      tags: ["web"],
      timeline: "some timeline data",
      status: "Cancelled",
      milestone: "Next milestone: in 3 days",
      task: "Follow up with manager",
    },
    {
        id: "5",
        heading: "Make an E-Commerce Website for a Brand Store",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Ongoing",
        milestone: "Next milestone: Dec 5th",
        task: "Follow up with manager",
      },
      {
        id: "6",
        heading: "Website technical maintenance project",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: Jan 1st",
        task: "Follow up with manager",
      },
      {
        id: "7",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Drafts",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "8",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Cancelled",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "9",
        heading: "Make an E-Commerce Website for a Brand Store",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Ongoing",
        milestone: "Next milestone: Dec 5th",
        task: "Follow up with manager",
      },
      {
        id: "10",
        heading: "Website technical maintenance project",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: Jan 1st",
        task: "Follow up with manager",
      },
      {
        id: "11",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Drafts",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "12",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "13",
        heading: "Make an E-Commerce Website for a Brand Store",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Ongoing",
        milestone: "Next milestone: Dec 5th",
        task: "Follow up with manager",
      },
      {
        id: "14",
        heading: "Website technical maintenance project",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: Jan 1st",
        task: "Follow up with manager",
      },
      {
        id: "15",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Drafts",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "16",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "17",
        heading: "Make an E-Commerce Website for a Brand Store",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Ongoing",
        milestone: "Next milestone: Dec 5th",
        task: "Follow up with manager",
      },
      {
        id: "18",
        heading: "Website technical maintenance project",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: Jan 1st",
        task: "Follow up with manager",
      },
      {
        id: "19",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Drafts",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
      {
        id: "20",
        heading: "WordPress website speed and SEO Optimization",
        tags: ["web"],
        timeline: "some timeline data",
        status: "Completed",
        milestone: "Next milestone: in 3 days",
        task: "Follow up with manager",
      },
    
  
    // more objects representing data for other items
  ];